---
# file: mini-seqware-install.yml
# This file is used for installing just SeqWare White Star as the bare-bones minimum to run SeqWare workflows

# The grid master depends on the hosts file, as we need to know at least who we
# are by this stage.
- hosts: master
  sudo: True
  roles:
    - { role: java, java_provider: Oracle8 }
    - { role: seqware-code,
          seqware_provider: artifactory ,
          user_name: seqware,
          setup_hdfs_user: False,
          create_user: False,
          workflow_engine: whitestar,
          sw_metadata_method: inmemory,
          oozie_work_dir: /datastore
      }

- hosts: master
  sudo: True
  roles:
    - { role: seqware-helloworld, user_name: seqware }
